"""empty message

Revision ID: 401dfc183ac6
Revises: 
Create Date: 2017-10-17 21:17:45.241021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401dfc183ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_doacao',
    sa.Column('id_td', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_td')
    )
    op.create_table('tipo_instituicoes',
    sa.Column('id_ti', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_ti')
    )
    op.create_table('tipo_usuarios',
    sa.Column('id_tu', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_tu')
    )
    op.create_table('usuarios',
    sa.Column('id_u', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('tipo_u', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_u'], ['tipo_usuarios.id_tu'], ),
    sa.PrimaryKeyConstraint('id_u'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('instituicoes',
    sa.Column('id_i', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('id_u', sa.Integer(), nullable=True),
    sa.Column('tipo_i', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_u'], ['usuarios.id_u'], ),
    sa.ForeignKeyConstraint(['tipo_i'], ['tipo_instituicoes.id_ti'], ),
    sa.PrimaryKeyConstraint('id_i')
    )
    op.create_table('avaliacoes',
    sa.Column('id_a', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('id_u', sa.Integer(), nullable=True),
    sa.Column('id_i', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_i'], ['instituicoes.id_i'], ),
    sa.ForeignKeyConstraint(['id_u'], ['usuarios.id_u'], ),
    sa.PrimaryKeyConstraint('id_a')
    )
    op.create_table('denuncia',
    sa.Column('id_den', sa.Integer(), nullable=False),
    sa.Column('id_u', sa.Integer(), nullable=True),
    sa.Column('id_i', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_i'], ['instituicoes.id_i'], ),
    sa.ForeignKeyConstraint(['id_u'], ['usuarios.id_u'], ),
    sa.PrimaryKeyConstraint('id_den')
    )
    op.create_table('doacao',
    sa.Column('id_d', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('id_i', sa.Integer(), nullable=True),
    sa.Column('id_td', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_i'], ['instituicoes.id_i'], ),
    sa.ForeignKeyConstraint(['id_td'], ['tags_doacao.id_td'], ),
    sa.PrimaryKeyConstraint('id_d')
    )
    op.create_table('endereco_instituicoes',
    sa.Column('id_ei', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('id_i', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_i'], ['instituicoes.id_i'], ),
    sa.PrimaryKeyConstraint('id_ei')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endereco_instituicoes')
    op.drop_table('doacao')
    op.drop_table('denuncia')
    op.drop_table('avaliacoes')
    op.drop_table('instituicoes')
    op.drop_table('usuarios')
    op.drop_table('tipo_usuarios')
    op.drop_table('tipo_instituicoes')
    op.drop_table('tags_doacao')
    # ### end Alembic commands ###
